### ISSUE TITLE
Improve text box look containing generated link

### ISSUE THREAD

**Issue by tamf** [tamf/whisper-secret-messages#66]
<img width="870" alt="Screen Shot 2021-07-12 at 2 23 14" src="https://user-images.githubusercontent.com/10188598/125204418-32daec00-e2b8-11eb-8ee1-0e6d3b5ca10f.png">

Increase border width for generated link -- not enough space. Also, make sure link has leading https:// 

I'm not sure exactly why, but the text box as is looks a bit off or too bare bones. Any other ways to make this box look better are welcome, including playing around with font or font size, or anything else

**Comment by swongg** [comment]
- will be included in my next PR

**Comment by swongg** [comment]
- will be included in my next PR

**Comment by swongg** [comment]
might make further design changes in the future. looks okay for now, not perfect.
