### ISSUE TITLE
Use toast message instead of alert 

### ISSUE THREAD

**Issue by tamf** [tamf/whisper-secret-messages#67]
Use toast message that fades away for Copied! notification. Alert is too intrusive

<img width="870" alt="Screen Shot 2021-07-12 at 2 26 05" src="https://user-images.githubusercontent.com/10188598/125204484-864d3a00-e2b8-11eb-8034-7d7c7b8ff444.png">

**Comment by swongg** [comment]
- will be included in my next PR
