### ISSUE TITLE
Display appropriate message to user in case of error

### ISSUE THREAD

**Issue by tamf** [tamf/whisper-secret-messages#73]
The following cases should be covered
- invalid link (the id doesn't exist or the secret has expired). Do not give details about why the link is invalid
- wrong passphrase

**Comment by swongg** [comment]
- will be included in my next PR

**Comment by swongg** [comment]
note: Currently displays same error message for invalid url and wrong passphrase. Need to create separate error message for wrong passphrase in a subsequent PR
